// import { defineConfig, env } from 'prisma/config'
import type { PrismaConfig } from 'prisma'
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'

export default {
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Fall back to process.env if the env() helper cannot be imported
    url: process.env.DATABASE_URL,
  },
} satisfies PrismaConfig
