name: Keep Workflow Active

on:
  schedule:
    - cron: '0 0 1 * *' # Monthly
  workflow_dispatch:       # Enable manual runs

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Keep alive
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keep alive [skip ci]"
          git push
